id = "gcode"
name = "G-code"
description = "G-code support."
version = "0.0.1"
schema_version = 1
authors = ["ChocolateNao <andrey12q112@gmail.com>"]
repository = "https://github.com/ChocolateNao/zed-gcode"

[grammars.gcode]
repository = "https://github.com/ChocolateNao/tree-sitter-gcode"
# v0.1.1
commit = "4c1afe6d2cc3c9946ad188fc74e17bb474d0e5c2"
