name = "G-code"
grammar = "gcode"
path_suffixes = [
  "ply",
  "sub",
  "g",
  "tap",
  "nc",
  "ncd",
  "gcode",
  "eia",
  "tcn",
  "fgc",
  "gp",
  "knc",
  "ssb",
  "dnc",
  "ncf",
  "xpi",
  "lib",
  "min",
  "nci",
  "fnc",
  "spf",
  "cnc",
  "din",
  "g00",
  "mmg",
  "ecs",
  "gcd",
  "m",
  "mpt",
  "ncg",
  "ncp",
  "sbp",
  "anc",
  "aptcl",
  "mpf",
  "hnc",
  "ngc",
  "prg",
  "pim",
  "apt",
  "001",
  "cls",
  "fan",
  "plt",
  "pu1",
  "pit",
  "rol",
  "S",
  "gc",
  "out"
]
line_comments = ["; ", "( ", " )"]
brackets = [{ start = "(", end = ")", close = true, newline = false }]
autoclose_before = ")"